import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Footer from './components/Footer'
import Navigation from './components/Navbar'
// import Hero from './components/Hero/Hero'


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Movie List',
  description: 'Generated by Moovie List',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    
    <html lang="en"
    
    >
         <body className={inter.className}>{children}
        
      <br /><br />
     
      <Footer/>
      
     
      </body>
    </html>
  )
}
